# CI to recreate and submit an AML pipeline when the code changes
variables:
  - group: aiml50-demo

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: 1.$(BuildID)$(Rev:.r)

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: '3.6'

- task: AzureCLI@1
  displayName: 'Install Azure ML CLI Extension'
  inputs:
    azureSubscription: $(subscription)
    scriptLocation: inlineScript
    inlineScript: 'az extension add -n azure-cli-ml'

- script: 'pip install --upgrade azureml-sdk'
  displayName: 'Install AzureML'

- task: AzureCLI@1
  displayName: 'Recreate and submit pipeline'
  inputs:
    azureSubscription: $(subscription)
    scriptLocation: inlineScript
    inlineScript: |
      cd aiml50/source
      subscription_id=$(az account show --query id -o tsv)
      azure_storage_account="$(session)$(event)storage"
      workspace="$(session)$(event)"
      azure_storage_key=$(az storage account keys list --account-name $azure_storage_account --resource-group $(resource_group) --query '[].value | [0]' -o tsv )
      echo 'running python script:'
      python setup_pipeline.py -d $(datastorename) -p $(datastorepath) -c $(computetarget) -v $(Build.BuildNumber) -s $subscription_id -r $(resource_group) -a $azure_storage_account -k $azure_storage_key -w $workspace

- task: CopyFiles@2
  displayName: 'Copy inference and deployment files'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/aiml50/source/'
    Contents: |
      deploymentconfig.json
      inferenceconfig.json
      score.py
      seer_scoring.yml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureCLI@1
  displayName: 'Publish package'
  env:
    AZURE_DEVOPS_EXT_PAT: $(access_token)
  inputs:
    azureSubscription: $(subscription)
    scriptLocation: inlineScript
    inlineScript: |
      az extension add -n azure-devops
      cd aiml50/source
      az artifacts universal publish \
        --organization "https://dev.azure.com/$(org_name)/" \
        --feed "SeerPackages" \
        --name "seer_deployment" \
        --version "$(Build.BuildNumber)" \
        --description "Seer files" \
        --path .
